const api=require("../../services/api");const storage=require("../../utils/storage");const {value,showError,eventToStory}=require("../../utils/ui");
Page({
 data:{loading:true,demo:false,statusText:"正在同步副本状态...",currentTime:"--:--",countdown:"",stats:"",canEnter:false,buttonText:"进入副本",runActive:false,readyToSettle:false,resources:0,shop:[],story:null},
 onShow(){if(!storage.get(storage.KEYS.userId,"")){wx.reLaunch({url:"/pages/welcome/index"});return;}this.setData({demo:Boolean(storage.get(storage.KEYS.dungeonDemo,false))});this.load();},
 onPullDownRefresh(){this.load().finally(()=>wx.stopPullDownRefresh());},
 async load(){this.setData({loading:true});try{const [status,state]=await Promise.all([api.getDungeonStatus(this.data.demo),api.getCurrentSession()]);getApp().globalData.state=state;const run=status.run||{};const stats=(status.panel&&status.panel.currentStats)||{};this.setData({statusText:value(status.statusText,status.isOpen?"副本已开启":"副本尚未开放"),currentTime:value(status.currentTime,"--:--"),countdown:value(status.countdown,""),stats:`生命 ${stats.hp||0} · 攻击 ${stats.attack||0} · 防御 ${stats.defense||0} · 护盾 ${stats.shield||0}`,canEnter:Boolean(status.isOpen||status.demoMode||run.active||run.readyToSettle),buttonText:(run.active||run.readyToSettle)?"继续副本":"进入副本",runActive:Boolean(run.active),readyToSettle:Boolean(run.readyToSettle),resources:(state.progress&&state.progress.resourcePoints)||0,shop:state.shopItems||[]});}catch(error){showError(error,"副本状态加载失败");}finally{this.setData({loading:false});}},
 async demoChange(e){const demo=e.detail.value;storage.set(storage.KEYS.dungeonDemo,demo);this.setData({demo});await this.load();},
 async enter(){if(!this.data.canEnter){wx.showToast({title:"副本尚未开放",icon:"none"});return;}if(this.data.runActive||this.data.readyToSettle){wx.navigateTo({url:"/features/adventure/dungeon-run/index"});return;}this.setData({loading:true});try{await api.startDungeon(this.data.demo);wx.navigateTo({url:"/features/adventure/dungeon-run/index"});}catch(error){showError(error,"进入副本失败");}finally{this.setData({loading:false});}},
 buy(e){const item=this.data.shop[Number(e.currentTarget.dataset.index)];if(!item||item.purchased)return;wx.showModal({title:`兑换「${item.name}」`,content:`消耗 ${item.price} 资源点。${value(item.effect,"")}`,success:async res=>{if(!res.confirm)return;try{const result=await api.createPurchase(item.itemId);const story=eventToStory(result.event,"兑换成功");if(story)this.setData({story});await this.load();}catch(error){showError(error,"购买失败");}}});},closeStory(){this.setData({story:null});}
});
